services:
  plebindex01:
    build:
      context: ./plebindex
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./plebindex/src:/app/src
      - ./plebindex/pages:/app/pages
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_APP_TITLE=${NEXT_PUBLIC_APP_TITLE}
      - NEXT_PUBLIC_APP_DESCRIPTION=${NEXT_PUBLIC_APP_DESCRIPTION}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  crawler01:
    build:
      context: ./crawler
      args:
        PLEBBIT_WS_URL: ${PLEBBIT_WS_URL}
        OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
        OPENROUTER_MODEL: ${OPENROUTER_MODEL}
        OPENROUTER_MODEL_B: ${OPENROUTER_MODEL_B}
        OPENROUTER_MODEL_C: ${OPENROUTER_MODEL_C}
        SITE_URL: ${SITE_URL}
        SITE_NAME: ${SITE_NAME}
        CONTENT_MODERATION_INTERVAL: ${CONTENT_MODERATION_INTERVAL}
        QUEUE_REFRESH_INTERVAL: ${QUEUE_REFRESH_INTERVAL}
        ENABLE_CONTENT_MODERATION: ${ENABLE_CONTENT_MODERATION}
    ports:
      - "3001:3001"
    volumes:
      - ./data/plebbit:/app/data
    environment:
      - PLEBBIT_WS_URL=${PLEBBIT_WS_URL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - OPENROUTER_MODEL_B=${OPENROUTER_MODEL_B}
      - OPENROUTER_MODEL_C=${OPENROUTER_MODEL_C}
      - SITE_URL=${SITE_URL}
      - SITE_NAME=${SITE_NAME}
      - CONTENT_MODERATION_INTERVAL=${CONTENT_MODERATION_INTERVAL}
      - QUEUE_REFRESH_INTERVAL=${QUEUE_REFRESH_INTERVAL}
      - ENABLE_CONTENT_MODERATION=${ENABLE_CONTENT_MODERATION}
      - DB_PATH=/app/data/plebbit_posts.db
    depends_on:
      - plebbit-cli
    extra_hosts:
      - "host.docker.internal:host-gateway"

  plebbit-cli:
    build: ./plebbit-cli
    image: plebbit-cli
    ports:
      - "9138:9138"
    volumes:
      - ./plebbit-cli/start-plebbit.sh:/start-plebbit.sh:ro
      - ./data/plebbit:/app/data
    command: ["sh", "-c", "/app/plebbit-cli/bin/run daemon --plebbitOptions.dataPath /app/data"]
  nginx:
    image: nginx:1.22.0
    environment:
      - SERVER_NAME=${SERVER_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/docker-entrypoint.d/:/docker-entrypoint.d/
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/docker-entrypoint.sh"
    command: ["nginx"]
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12d; done;'"