services:
  plebindex:
    build:
      context: ./plebindex
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - plebbit_db:/app/plebbit_db
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  crawler:
    build: ./crawler
    ports:
      - "3001:3001"
    volumes:
      - plebbit_db:/app/plebbit_db
    environment:
      - PLEBBIT_WS_URL=ws://plebbit-cli:9138/AUUz0CPyTwcSJct1zVyE9nYVtKKk3Fb4RbwbcSyw
    # depends_on:
      # - plebbit-cli
    extra_hosts:
      - "host.docker.internal:host-gateway"

  plebbit-cli:
    build: ./plebbit-cli
    image: plebbit-cli
    ports:
      - "9138:9138"
    volumes:
      - plebbit_db:/app/plebbit_db
    command: ["/app/plebbit-cli/bin/run", "daemon"]
  nginx:
    image: nginx:1.22.0
    depends_on:
      - plebindex
    environment:
      - SERVER_NAME=${SERVER_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/docker-entrypoint.d/:/docker-entrypoint.d/
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/docker-entrypoint.sh"
    command: ["nginx"]
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  plebbit_db:
